# Copyright HeteroCL authors. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

# pyproject.toml
[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra"
testpaths = [
    "tests",
]
norecursedirs = [
    "tests/hcl-mlir",
    "tests/polybench",
]
